CHECK_INS_PORT: "8002"
CHECK_INS_MONGO_DB_NAME: contact_tracker
CHECK_INS_MONGO_HOST:
CHECK_INS_MONGO_USER:
CHECK_INS_MONGO_PWD:
PLACES_PORT: "8003"
PLACES_MONGO_DB_NAME: contact_tracker
PLACES_MONGO_HOST:
PLACES_MONGO_USER:
PLACES_MONGO_PWD:
USERS_PORT: "8004"
USERS_MONGO_DB_NAME: contact_tracker
USERS_MONGO_HOST:
USERS_MONGO_USER:
USERS_MONGO_PWD:
APIGATEWAY_PORT: "8080"
JWT_KEY_PATH: ./id_rsa.pub
JWT_SECRET_PATH: ./id_rsa
JWT_ACCESS_EXPIR: 20160
JWT_REFRESH_EXPIR: 20160
RPC_AUTH_PWD: ct123$!
TIMEZONE: America/New_York
SMTP_HOST: "smtp.gmail.com"
SMTP_PORT: "587"

NOTIFICATIONS_FROM_EMAIL: "tlee872@gmail.com"
EMAIL_PWD: "password123"
STORE_PWD: password123
